### ISSUE TITLE
Different thresholds for cell-free droplets

### ISSUE THREAD

**Issue by cnk113** [CaibinSh/scAR-reproducibility#4]
Hello,

I noticed in the scRNA-seq and CRISPR screen tutorial you had different thresholds for the cell-free and droplet cutoffs.
I'm assuming the most important part is the cell-free portion, which should be under and after the knee like the 20k hgmm sample?
Or would it much after the knee like the A549 sample?
I'm mainly using this for CRISPR guide calling if that helps guide your advice.
![image](https://user-images.githubusercontent.com/21249710/159140395-fa5bf59e-93fb-4283-9b32-6544bdb56dde.png)
![image](https://user-images.githubusercontent.com/21249710/159140401-a4e0bce2-617a-48c1-9cf8-94e4e1e5378f.png)

Thanks,
Chang

**Comment by CaibinSh** [comment]
Hi @cnk113 ,

Thanks for pointing this out. It was a little mistake, I have redone and uploaded the kneeplot, please see the attached plot.

Yes, the cell-free proportion correlates stronger with the cells, so we think it reflect the ambient noise better. In my experience, it does not make a big difference for a single-cell-line data, which is to say, you could even use the cell population to calculate ambient profile. But in the case of multiple cell types, we observed that ambient profiles can be different between different subpopulations of droplets.

![image](https://user-images.githubusercontent.com/43896555/159567351-39a97333-7776-4257-93e9-8359e4b09984.png)

**Comment by cnk113** [comment]
Thanks one more question, I noticed in the scRNA-seq denoising you used "cell-free droplets" for the ambient pool
However in the guide calling you use the "cells" portion which would mean your ambience includes "other" and "cell-free droplets". I was wondering what the reasoning for the different approach?

**Comment by CaibinSh** [comment]
> 
You are welcome.
This experiment uses a single cell line and we observed that ambient frequencies of sgRNAs are not significantly different between "other" and "cell-free droplets" in single cell line CRISPR screening experiments. So I just calculated the ambient profile using every droplet (excluding "cells") for simplicity (You could also use "cell-free droplets").

I'm eager to receive your feedback on whether scAR improves your assignment once you try it.

**Comment by cnk113** [comment]
Hey Caibin,

It actually called way more, and theres only minor discrepancy in the intersection of the calls so I'll be using scAR from now on. Thanks!

Best,
Chang

**Comment by CaibinSh** [comment]
> 

Glad to hear that scAR also works for you, Chang.

All the best for your project,
Caibin
