### ISSUE TITLE
Tutorial for CRISPR screen?

### ISSUE THREAD

**Issue by cnk113** [CaibinSh/scAR-reproducibility#5]
Hello,

In your preprint you used scAR to denoise the sgRNA calls, I was wondering if you could provide a tutorial for that?

Best,
Chang

**Comment by CaibinSh** [comment]
Hi Chang,

Thanks for your interest. 
Sure, I am working on this, it will be updated soon. Please keep eyes on this ticket or the README file. I will update it once done.

Best,
Caibin

**Comment by CaibinSh** [comment]
Hi @cnk113 ,

The tutorials has been added, you can find the link in the README file.
Hope it works for you. Any feedback is welcome!

Best, Caibin
