### ISSUE TITLE
Setting UMI count threshold to determine cell-free droplets

### ISSUE THREAD

**Issue by mdmanurung** [CaibinSh/scAR-reproducibility#7]
Dear authors,

Is it correct to take all droplets with <12 UMI counts as the cell-free droplets or is there a heuristic to determine it?

I am looking forward to use this package!

Regards,
Mikhael

**Comment by CaibinSh** [comment]
Hi Mikhael,

Thanks for your interest.

We recommend using a knee-plot of mRNA UMI counts to determine the threshold of cell-free droplets, as the threshold may vary across datasets. In the future, we may implement some algorithms (such as DropletQC) to automatically determine cell-free droplets.
![image](https://user-images.githubusercontent.com/43896555/153387565-f93bba33-d530-4547-a092-49dde2feb99a.png)

The principle is **to exclude any droplets that contain a cell or possibly contain cell debris**. Of course, the more cell-free droplets, the higher confidence.

A suboptimal option is to not use cell-free droplets (default setting). scAR will estimate the background frequencies by averaging cells.

Best, Caibin

**Comment by mdmanurung** [comment]
Thanks for your reply, Caibin!
