### ISSUE TITLE
dataloader obsolete

### ISSUE THREAD

**Issue by viveksagar-kr** [CaibinSh/scAR-reproducibility#8]
"from . import _data_loader as dataloader" in line 4 of __main.py__ is throwing an exception. As the module is obsolete, removing the import statement will fix the issue

**Comment by CaibinSh** [comment]
> "from . import _data_loader as dataloader" in line 4 of **main.py** is throwing an exception. As the module is obsolete, removing the import statement will fix the issue

Thanks, Vivek. You are right. This statement can be removed. Will be fixed in release v0.1.2-beta.

In addition, a statement of '# -*- coding: utf-8 -*-' has been added to 1st line of _data_loader.py to avoid the error of 'SyntaxError: Non-ASCII character '\xe2' '.

**Comment by viveksagar-kr** [comment]
Fixed in version v0.1.2
